version: 0.0
os: linux
files:
  - source: /
    destination: /opt/plugin/.hidden-p/IRMS-backend
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: pipelines/integrations-deployment-pre-post.sh
